#!/bin/bash -e
###########################################################
# Back up MySQL databases
###########################################################

. /usr/local/bin/umbrella.sh        # source Umbrella Linux variables

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
PATH="$PATH:/usr/local/mysql/bin"

# My config
BACKUP_DIR="."

# Do not backup these databases
IGNORE="information_schema performance_schema"

# Get list of all databases
DB_LIST=`mysql -h localhost -Bse 'show databases'`

for db in $DB_LIST; do

        # set skip variable
        skip=0

        if [ "$IGNORE" != "" ]; then
                for i in $IGNORE; do
                        [ "$db" == "$i" ] && skip=1 || :
                done
        fi

        if [ "$skip" == "0" ]; then
                mysqldump --skip-lock-tables --events -h localhost $db | gzip -9 > $BACKUP_DIR/${HOST_ARCHIVE}_$db.sql.gz
        fi

done

exit 0
