#!/bin/sh

if [ -e /usr/bin/simple-scan ]; then
    echo group:simple-scan
fi

if [ -e /bin/ntfs-3g ]; then
    echo group:ntfs-3g
fi

if grep -q '^\S*\s*\S*\s*xfs\s' /etc/fstab; then
    echo group:fs-xfs
fi

if [ -e /sbin/lvm ]; then
    echo group:lvm
fi

if [ -e /sbin/mdadm ]; then
    echo group:mdraid
fi

if [ -e /usr/sbin/grub ]; then
    echo group:grub-legacy
fi

if [ -e /usr/bin/skypeforlinux ]; then
    echo group:skype
fi

if [ -e /usr/bin/acroread ]; then
    echo group:adobe-reader
fi

if ls /boot/vmlinuz-*-generic.efi.signed 1> /dev/null 2>&1; then
    echo group:kernel-signed
fi

# detect if other OS are installed
if [ -e /usr/bin/os-prober ]; then
    if [ -n "$(os-prober)" ]; then
        echo group:other-OS
    fi
fi

# detect if lxd containers are defined on this host
if [ -d "/var/lib/lxd/containers" ]; then
    CONTCNT=`ls -d1 /var/lib/lxd/containers/*/ 2>/dev/null| wc -l`
    if [ "$CONTCNT" -gt "0" ]; then
        echo "group:lxd-containers-defined"
    fi
fi
